name: Adam Wilson
favicon: null
layout_spectrum: 0.26558984024450183
typography_spectrum: 0.15316689992323518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6290640651714057
  lightness: 0.8348417892120779
  saturation: 0.1860149463173002
  rhythmicContrast: 0.09554253099486232
purpose: []
